# Generated by Django 4.2.16 on 2024-11-19 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursosabiertos',
            name='idasignacion',
        ),
    ]
