# Generated by Django 4.2.16 on 2024-11-19 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_remove_cursosabiertos_idasignacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursosabiertos',
            old_name='idcursoaberto',
            new_name='idcursoabierto',
        ),
        migrations.AlterUniqueTogether(
            name='cursosabiertos',
            unique_together={('idcursoabierto', 'idplan', 'idcurso')},
        ),
    ]
