# Generated by Django 4.2.16 on 2024-11-19 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_profesores_ap_materno_profesores_ap_paterno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesores',
            old_name='username',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='profesores',
            name='ap_materno',
        ),
        migrations.RemoveField(
            model_name='profesores',
            name='ap_paterno',
        ),
        migrations.RemoveField(
            model_name='profesores',
            name='nombres',
        ),
    ]
