# Generated by Django 4.2.16 on 2024-11-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_rename_username_profesores_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesores',
            name='id',
        ),
        migrations.AddField(
            model_name='profesores',
            name='ap_materno',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profesores',
            name='ap_paterno',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profesores',
            name='nombres',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
