# Generated by Django 4.2.16 on 2024-11-22 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_rename_idcursoaberto_asignacionprofesores_idcursoabierto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoponderacion',
            fields=[
                ('idtipoponderacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'tipoponderacion',
            },
        ),
        migrations.AddField(
            model_name='cursosabiertos',
            name='cupos',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='cursosabiertos',
            name='horasasincronicas',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='cursosabiertos',
            name='horassincronicas',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='ponderaciones',
            name='idtipoponderacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.tipoponderacion'),
        ),
    ]
