# Generated by Django 4.2.16 on 2024-12-12 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_tipoponderacion_cursosabiertos_cupos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioDetalles',
            fields=[
                ('idcalendariodetalle', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(null=True)),
                ('hora', models.TimeField(null=True)),
                ('duracion', models.TimeField(null=True)),
                ('activo', models.BooleanField(default=True)),
                ('idcursoabierto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.cursosabiertos')),
            ],
            options={
                'verbose_name': 'calendariodetalles',
                'unique_together': {('idcalendariodetalle', 'idcursoabierto')},
            },
        ),
    ]
