# Generated by Django 4.2.16 on 2024-12-12 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_calendariodetalles'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursosabiertos',
            name='aprueba',
            field=models.IntegerField(default=70),
        ),
    ]
