# Generated by Django 4.2.16 on 2024-12-16 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0002_alter_bancopreguntas_idcurso_and_more'),
        ('lms', '0012_alter_miscursos_options_notas'),
        ('cms', '0011_cursosabiertos_aprueba'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AsignacionProfesores',
            new_name='AsignacionProfesore',
        ),
        migrations.RenameModel(
            old_name='CalendarioDetalles',
            new_name='CalendarioDetalle',
        ),
        migrations.RenameModel(
            old_name='Cursos',
            new_name='Curso',
        ),
        migrations.RenameModel(
            old_name='Cursosabiertos',
            new_name='Cursosabierto',
        ),
        migrations.RenameModel(
            old_name='PlanEstudios',
            new_name='PlanEstudio',
        ),
        migrations.RenameModel(
            old_name='ponderaciones',
            new_name='ponderacione',
        ),
        migrations.RenameModel(
            old_name='Profesores',
            new_name='Profesore',
        ),
    ]
