# Generated by Django 5.1.2 on 2024-11-09 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BancoPreguntas',
            fields=[
                ('idpregunta', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'bancopreguntas',
            },
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('idcurso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'cursos',
            },
        ),
        migrations.CreateModel(
            name='PlanEstudios',
            fields=[
                ('idplan', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'planestudios',
            },
        ),
        migrations.CreateModel(
            name='BancoRespuestas',
            fields=[
                ('idrespuesta', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('idpregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.bancopreguntas')),
            ],
            options={
                'verbose_name': 'bancorespuestas',
            },
        ),
        migrations.CreateModel(
            name='BancoResultados',
            fields=[
                ('idresultado', models.AutoField(primary_key=True, serialize=False)),
                ('resultado', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('idpregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.bancopreguntas')),
                ('idrespuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.bancorespuestas')),
            ],
        ),
        migrations.AddField(
            model_name='bancopreguntas',
            name='idcurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.cursos'),
        ),
        migrations.AddField(
            model_name='cursos',
            name='idplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.planestudios'),
        ),
        migrations.AddField(
            model_name='bancopreguntas',
            name='idplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.planestudios'),
        ),
        migrations.AlterUniqueTogether(
            name='cursos',
            unique_together={('idcurso', 'idplan')},
        ),
    ]
