# Generated by Django 5.1.2 on 2024-11-13 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_notas_ponderaciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MisCursos',
            fields=[
                ('idmiscurso', models.AutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('idcurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.cursos')),
                ('idplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.planestudios')),
            ],
        ),
    ]
