# Generated by Django 4.2.16 on 2024-11-13 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0003_miscursos'),
    ]

    operations = [
        migrations.AddField(
            model_name='miscursos',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Cursosabiertos',
            fields=[
                ('idcursoaberto', models.AutoField(primary_key=True, serialize=False)),
                ('fechainicio', models.DateField()),
                ('fechafin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('idcurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.cursos')),
                ('idplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.planestudios')),
            ],
        ),
    ]
