# Generated by Django 4.2.16 on 2024-11-13 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_miscursos_username_cursosabiertos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miscursos',
            name='idcurso',
        ),
        migrations.RemoveField(
            model_name='miscursos',
            name='idplan',
        ),
        migrations.AddField(
            model_name='miscursos',
            name='idcursoabierto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.cursosabiertos'),
        ),
    ]
