# Generated by Django 4.2.16 on 2024-11-13 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0005_remove_miscursos_idcurso_remove_miscursos_idplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursosabiertos',
            name='admisionfin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='cursosabiertos',
            name='admisioninicio',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cursosabiertos',
            name='fechafin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='cursosabiertos',
            name='fechainicio',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('idprofesor', models.AutoField(primary_key=True, serialize=False)),
                ('rutpasaporte', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=200)),
                ('comuna', models.CharField(max_length=200)),
                ('fono', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cursosabiertos',
            name='idprofesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.profesores'),
        ),
    ]
