# Generated by Django 4.2.16 on 2024-11-13 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_cursosabiertos_admisionfin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursosabiertos',
            old_name='idprofesor',
            new_name='idasignacion',
        ),
        migrations.CreateModel(
            name='AsignacionProfesores',
            fields=[
                ('idasignacion', models.AutoField(primary_key=True, serialize=False)),
                ('activo', models.BooleanField(default=True)),
                ('idcursoaberto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.cursosabiertos')),
                ('idprofesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.profesores')),
            ],
        ),
    ]
