# Generated by Django 4.2.16 on 2024-11-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_rename_idprofesor_cursosabiertos_idasignacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursosabiertos',
            name='imgcurso',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
