# Generated by Django 4.2.16 on 2024-11-14 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0008_cursosabiertos_imgcurso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miscursos',
            name='username',
        ),
        migrations.AddField(
            model_name='miscursos',
            name='iduser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='ponderaciones',
            unique_together={('idponderacion', 'idplan')},
        ),
        migrations.RemoveField(
            model_name='ponderaciones',
            name='idcurso',
        ),
    ]
