# Generated by Django 4.2.16 on 2024-11-14 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_remove_miscursos_username_miscursos_iduser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miscursos',
            old_name='iduser',
            new_name='username',
        ),
    ]
