# Generated by Django 4.2.16 on 2024-11-19 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0002_alter_bancopreguntas_idcurso_and_more'),
        ('cms', '0001_initial'),
        ('lms', '0010_rename_iduser_miscursos_username'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cursos',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cursos',
            name='idplan',
        ),
        migrations.RemoveField(
            model_name='cursosabiertos',
            name='idasignacion',
        ),
        migrations.RemoveField(
            model_name='cursosabiertos',
            name='idcurso',
        ),
        migrations.RemoveField(
            model_name='cursosabiertos',
            name='idplan',
        ),
        migrations.AlterUniqueTogether(
            name='notas',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='notas',
            name='idcurso',
        ),
        migrations.RemoveField(
            model_name='notas',
            name='idplan',
        ),
        migrations.AlterUniqueTogether(
            name='ponderaciones',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ponderaciones',
            name='idplan',
        ),
        migrations.RemoveField(
            model_name='profesores',
            name='username',
        ),
        migrations.AlterField(
            model_name='miscursos',
            name='idcursoabierto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.cursosabiertos'),
        ),
        migrations.DeleteModel(
            name='AsignacionProfesores',
        ),
        migrations.DeleteModel(
            name='Cursos',
        ),
        migrations.DeleteModel(
            name='Cursosabiertos',
        ),
        migrations.DeleteModel(
            name='Notas',
        ),
        migrations.DeleteModel(
            name='PlanEstudios',
        ),
        migrations.DeleteModel(
            name='ponderaciones',
        ),
        migrations.DeleteModel(
            name='Profesores',
        ),
    ]
