# Generated by Django 4.2.16 on 2024-11-11 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lms', '0002_notas_ponderaciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BancoPreguntas',
            fields=[
                ('idpregunta', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('idcurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.cursos')),
                ('idplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.planestudios')),
            ],
            options={
                'verbose_name': 'bancopreguntas',
            },
        ),
        migrations.CreateModel(
            name='BancoRespuestas',
            fields=[
                ('idrespuesta', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('idpregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostico.bancopreguntas')),
            ],
            options={
                'verbose_name': 'bancorespuestas',
            },
        ),
        migrations.CreateModel(
            name='BancoResultados',
            fields=[
                ('idresultado', models.AutoField(primary_key=True, serialize=False)),
                ('resultado', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('idpregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostico.bancopreguntas')),
                ('idrespuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostico.bancorespuestas')),
            ],
            options={
                'verbose_name': 'bancoresultados',
                'unique_together': {('idresultado', 'idpregunta', 'idrespuesta')},
            },
        ),
    ]
