# Generated by Django 4.2.16 on 2024-12-16 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_rename_asignacionprofesores_asignacionprofesore_and_more'),
        ('diagnostico', '0002_alter_bancopreguntas_idcurso_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BancoPreguntas',
            new_name='BancoPregunta',
        ),
        migrations.RenameModel(
            old_name='BancoRespuestas',
            new_name='BancoRespuesta',
        ),
        migrations.RenameModel(
            old_name='BancoResultados',
            new_name='BancoResultado',
        ),
    ]
